spring:
  notification:
    email:
      enabled: true
      host: ${MAIL_HOST:smtp.gmail.com}
      port: ${MAIL_PORT:587}
      username: ${MAIL_USERNAME:luizfernandesoliveiraff@gmail.com}
      password: ${MAIL_PASSWORD:sknfztlbdmqmippu}
